FROM eboraas/apache-php

#It is all about me
MAINTAINER Jonathan Hill <jonathan.hill@vistronix.com>

#Pass in the database connection information
#ARG DB_CONN 
#ARG DB_USER 
#ARG DB_PWD  

#Set a bunch of enviornmental variables for reference later
ENV MODOWA_PKG=unix_all.tgz \
    CLIENT_INSTALL=instantclient.tar \
    ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/instantclient_12_1 \
    LD_LIBRARY_PATH=/opt/oracle/instantclient_12_1:$LD_LIBRARY_PATH \
    WEB_HOME=/var/www/html \
    HTTPD_CONF=/etc/apache2/apache2.conf \
    MOD_LOC=/etc/apache2/mods-available \
    APACHE_LOC=/usr/lib/apache2

#CREATE ORACLE_HOME
RUN mkdir $ORACLE_BASE

#Copy over the files we need
COPY ./public-html/ $WEB_HOME/
COPY $MODOWA_PKG $CLIENT_INSTALL $ORACLE_BASE/
COPY modowa.conf $MOD_LOC/
#Install prerequisites
RUN apt update && \
    apt upgrade -y && \
    apt-get install -y libaio1
#RUN apt-get install unzip

#Unzip and build the shit we need
#Setup the instant client
RUN cd $ORACLE_BASE && \
    tar -xzvf $CLIENT_INSTALL && \
    cd $ORACLE_HOME && \
    ln -s libclntsh.so.12.1 libclntsh.so && \
    ln -s libocci.so.12.1 libocci.so && \
    ln -s libclntsh.so.12.1 libclntsh.so.11.1

#build modowa
RUN cd $ORACLE_BASE && \
    tar -xzvf $MODOWA_PKG && \
    cd modowa/apache24 && \
#    make -kf modowa.mk && \
    cp mod_owa.so $APACHE_LOC/modules/

     

#Create the modowa conf file
#RUN

#Append the modowa conf file to the httpd.conf file
#RUN echo "Include conf/modowa.conf" >> $HTTPD_CONF
